export const NavData=[
    {
        path:"/",
        xs:1,
        label:"AddUser"
    },
    {
        path:"/showuser",
        xs:1,
        label:"ShowUser"
    },
    {
        path:"/addclass",
        xs:2,
        label:"Addclass"
    },
    {
        path:"/class",
        xs:1,
        label:"Classes"
    },
    {
        path:"/adddiv",
        xs:1,
        label:"AddDivision"
    },
    
    {
        path:"/divs",
        xs:1,
        label:"Division"
    },
    {
        path:"/addhouse",
        xs:2,
        label:"AddHouse"
    },
    {
        path:"/houses",
        xs:1,
        label:"Houses"
    },
    {
        path:"/stud",
        xs:1,
        label:"Students"
    },
    {
        path:"/addstud",
        xs:2,
        label:"Add Students"
    },
    {
        path:"/game",
        xs:2,
        label:"Games"
    },
    {
        path:"/addgame",
        xs:2,
        label:"AddGames"
    },
    {
        path:"/studentdetail",
        xs:2,
        label:"StudentsDetails"
    },
    {
        path:"/showdetail",
        xs:3,
        label:"ShowStudentsDetail"
    }
]